version: '3.3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=mops
      - POSTGRES_PASSWORD=mops
      - POSTGRES_DB=moepsinnen
  mops:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'