version: '3.3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=mops
      - POSTGRES_PASSWORD=mops
      - POSTGRES_DB=moepsinnen
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
  mops:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
volumes:
  postgres: