name: Checkstyle & Spotbugs

on: 
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron:  '0 12,13,14,15,16,17,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java v11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run Tests with Gradle
      run: ./gradlew check
