name: Tests-on-Ubutnu

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  Tests-on-Ubutnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java v11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests with Gradle
        run: ./gradlew test
